kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.mpp.enableCInteropCommonization=true
kotlin.suppressGradlePluginWarnings=IncorrectCompileOnlyDependencyWarning

org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true

android.nonTransitiveRClass=true
android.useAndroidX=true

GROUP=dev.brahmkshatriya.wasmtime
VERSION=0.1.0-SNAPSHOT
